version: "3.7"

services:
  analytics-couchdb:
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    volumes:
      - analytics_data:/opt/couchdb/data

volumes:
  analytics_data:
