name: "Dependency-Aware Fabric Evaluation"
version: "2.0.0"

caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: true
    useGateway: true
    discovery:
      enabled: false
      asLocalhost: false
    connectionOptions:
      discovery:
        timeout: 100000
      query:
        timeout: 100000

channels:
  - channelName: mychannel
    contracts:
      - id: fabcar
      - id: marbles
      - id: smallbank
      - id: asset-transfer-basic
      - id: token-erc20
      - id: commercial-paper
      - id: auction

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '../crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '../crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem'
        - name: 'Admin'
          admin: true
          clientPrivateKey:
            path: '../crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '../crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem'
    connectionProfile:
      path: './connection-profile.yaml'
      discover: false
